### ISSUE TITLE
Add link to the "Create a Data Space" button

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#100]
@MdechampG commented on [Wed Oct 26 2022](https://github.com/okp4/kanban/issues/894)

When the user clicks on the button "Create a new Data Space" he should be redirected on this link (mock up) :
 
https://xd.adobe.com/view/31a3d2a5-9f07-4e31-a612-20059ff929a5-64f0/screen/cf61fcae-4b18-4db6-9fe7-2aeec4deb5a6?fullscreen

**Comment by MdechampG** [comment]
@JulienMassonnat could you add a link on this mock up please ? https://xd.adobe.com/view/31a3d2a5-9f07-4e31-a612-20059ff929a5-64f0/screen/8b844c04-9896-48b4-b148-d530d591f0ab?fullscreen 

On the slide "Rulebook Display", if I click on the OKP4 logo, I am redirected to the portal (https://portal.staging.okp4.space/dataverse)

**Comment by MdechampG** [comment]
@RaphaelEscrig have you began this issue ?

**Comment by RaphaelEscrig** [comment]
@MdechampG Yes, this issue is done on my side and juste have been merged into master. It will be soon release on the staging environment.

**Comment by MdechampG** [comment]
Ok thank you @RaphaelEscrig

**Comment by MdechampG** [comment]
@JulienMassonnat has modified the mock up.
The OKP4 logo redirects to the url portal.okp4.space/dataverse
Today we can't test it because the prod is not operational yet.
