### ISSUE TITLE
Portal Explore Page

### ISSUE THREAD

**Issue by RaphaelEscrig** [okp4/portal-web#26]
### **Purpose**

Build the css layout of the portal explore page according to the frames below.
It has to be fully responsive.
 
### **Visual**
![Screenshot 2022-09-21 at 15 36 21](https://user-images.githubusercontent.com/33039052/191518464-212209a3-54d5-4221-bee6-f090e48f2929.png)
![Screenshot 2022-09-21 at 15 35 39](https://user-images.githubusercontent.com/33039052/191518309-6ab62711-3625-4590-bbe1-73a7db4a1991.png)

### **Use cases**

This page is the entry point to explore the Dataverse.

#### **Typology**

N/A

#### **Properties**

N/A

#### **State**

N/A

### **Notes**

The `Filters` part on the left will not be implemented for the moment, but a place is reserved for it to facilitate its integration later.

**Comment by henigh** [comment]
on https://portal.devnet.staging.okp4.space/dataverse/explore
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/39368385/199689391-4c281cf9-ed54-4e33-99e4-7bd91039bea0.png">

**Comment by MdechampG** [comment]
If we select the 2 data Spaces and we select `show 10`, we don't see all the datasets and services and it is not indicated. We miss a page numbering. 

![image](https://user-images.githubusercontent.com/92780073/199930950-f9df885a-0d2f-439a-b2d5-1cbafd2cc985.png)

**Comment by MdechampG** [comment]
Not necessary for MVP
