### ISSUE TITLE
Add a button "See in OKP4 BI"

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#45]
@MdechampG commented on [Fri Oct 07 2022](https://github.com/okp4/kanban/issues/843)

For the knowledge Datasets, we need a button to see the data in OKP4 BI. 

![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/f4e6f629-277d-4e53-ae71-46bf3af6715a)

When the user clicks on the button, a transaction is sent in the blockchain to trigger the "Data connector" service. 
The user has to validate the transaction with his Keplr wallet. 

Then OKP4 BI is opened in a new tab.

**Comment by fredericvilcot** [comment]
@MdechampG @henigh 
Could you please provide me the BI URL to redirect to?
Thx

**Comment by henigh** [comment]
Here it is ;) 
https://dashboards.staging.okp4.space/

**Comment by MdechampG** [comment]
If we do the demo on the staging yes it's good for me

**Comment by MdechampG** [comment]
@SonnevilleDamien : add the label "knowledge" in the json
