### ISSUE TITLE
Add "Rhizome governance" button on the portal

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#48]
@MdechampG commented on [Fri Oct 07 2022](https://github.com/okp4/kanban/issues/844)

There should be a button on the Rhizome portal to access to Rhizome governance summary (Page 29 of the [mock up](https://xd.adobe.com/view/31a3d2a5-9f07-4e31-a612-20059ff929a5-64f0/screen/d8a45cb1-7433-40b3-b6ce-4237bfcd0678))

![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/06bea9b7-b3ce-4cb1-946c-597cad3f8af8)

**Comment by henigh** [comment]
As seen with Marine and Lauren, Mock up should be dispalyed in [fullscreen mode](https://xd.adobe.com/view/31a3d2a5-9f07-4e31-a612-20059ff929a5-64f0/screen/d8a45cb1-7433-40b3-b6ce-4237bfcd0678/?fullscreen)

**Comment by MdechampG** [comment]
Following the discussion with @lolottetheclash and @henigh, here is the new mock up : 

![image](https://user-images.githubusercontent.com/92780073/196225453-2d90a12b-b484-448d-be10-a26d662466a5.png)
