### ISSUE TITLE
Decrease the size of the cards on the portal

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#50]
Current status of the portal : 

![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/1632c797-0192-4cc9-ab86-f1fd9ba51e6e) 

We should have only 3 cards (2 datasets and 1 service) in small size. 

We will provide the names later (when #49 will be done)

**Comment by fredericvilcot** [comment]
@ErikssonJoakim 
What about this one?

**Comment by MdechampG** [comment]
Following the discussion with @fredericvilcot : 

We should have 3 small cards per Data Space : 2 Datasets and 1 Service. 
- Datasets : the ones labelled as `knowledge`
- Service : the first in the json 

To do : 

- [ ] Change the size of the cards into small
- [ ] Add 2 "knowledge datasets" in the dataset.json file for the Know Universe DS @SonnevilleDamien 
- [ ] Place the service "Data Selector" in first position in the service.json file @SonnevilleDamien 
- [ ] Add a service in second position of the service.json file for Know Universe @SonnevilleDamien 
- [ ] Implement the request @RaphaelEscrig
