### ISSUE TITLE
Interact button

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#55]
Where are we redirected when we click on "Interact" ? 

Option 1 : Discord server
Option 2 : https://linktr.ee/okp4
Option 3 : No redirection
Option 4 : we remove the button

**Comment by MdechampG** [comment]
I propose to redirect on the channel `chat` of the OKP4 server 
https://discord.com/channels/946759919678406696/968040263006179358  

@henigh @LucasPzn is it ok for you ?

**Comment by henigh** [comment]
To go faster, I think it's ok 👍 
But I think we should absolutely change this if the context is different from a Demo. 

I mean if its for OKP4 Server, why not simply call it Discord ?

**Comment by MdechampG** [comment]
@henigh you're right and @ErikssonJoakim is integrating the discord logo in the footer. 
It will be redundant but it is better than option 3. 
We agree that it is only for the MVP demonstration.
