### ISSUE TITLE
Add Data Space filter in the Explorer

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#68]
Following the decision #54 we want to make understand what is the Dataverse in the demo.  

We should see in the Explorer : 
- The Data Space "Rhizome" and its datasets and services
- The Data Space "Know universe" and its datasets and services

The user should be able to filter on the Data Space. 
For the demo (deadline : end of October), we will not add any other filter in the Explorer. 

The filter will be a multiple select. 

Values:
- Rhizome
- Know universe

Default value : the two are selected 

Mock up : 

![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/6a261b4e-1c37-4b9a-9838-396b85f836af)

**Comment by RaphaelEscrig** [comment]
I think we can close this issue.

**Comment by MdechampG** [comment]
Default value : no filter selected -> We see all the objects

**Comment by MdechampG** [comment]
@fredericvilcot according the last comment the default value should be "nothing selected" but I have by default all DS selected 

![image](https://user-images.githubusercontent.com/92780073/211548996-f98bf4f2-f2d0-4fdc-8c24-f9a56487fc8d.png)

**Comment by fredericvilcot** [comment]
@MdechampG 
Sure, you are right, that's a miss.
It's fixed, you can test it and tell me 😌

**Comment by MdechampG** [comment]
Tested on https://portal.staging.okp4.space/dataverse/explore with Mozilla Firefox

When I arrive on the page : No filter selected and I see all resources of the Dataverse ✅ 
When I select only Rhizome : only Rhizome resources ✅ 
When I select only Know Universe : only Know universe resources ✅ 
When I select both : I see all resources of these 2 DS ✅
