### ISSUE TITLE
Add description of "Know Universe" Data Space on the portal

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#89]
The description of the Know Universe Data Space : 

French : Le Data Space Know Universe vise à valoriser des données financières inhérentes à l'économie du jeton $KNOW. Ces données peuvent par exemple être partagées par l'un des 150 validateurs de la blockchain OKP4. 

English : The Know Universe Data Space aims to leverage financials data inherent to the $KNOW token economy. This data can for example be shared by one of the 150 validators of the OKP4 blockchain. 

![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/54deb0b1-51e0-4661-964f-aad2c37c77f4)

**Comment by MdechampG** [comment]
I think we can close this issue ✅

**Comment by SonnevilleDamien** [comment]
Yes
