### ISSUE TITLE
Add description of "Know universe" in the Explorer

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#90]
The description of the Know Universe Data Space in the Explorer : 

French : Le Data Space Know Universe vise à valoriser des données financières inhérentes à l'économie du jeton $KNOW. Ces données peuvent par exemple être partagées par l'un des 150 validateurs de la blockchain OKP4. 

English : The Know Universe Data Space aims to leverage financials data inherent to the $KNOW token economy. This data can for example be shared by one of the 150 validators of the OKP4 blockchain. 

This should be changed here : https://github.com/okp4/portal-web/blob/main/data/dataspace.json

**Comment by MdechampG** [comment]
We can close this issue I think ✔️

**Comment by SonnevilleDamien** [comment]
Yes

**Comment by sasha27o** [comment]
si
