### ISSUE TITLE
Add "Home" in the portal's header

### ISSUE THREAD

**Issue by MdechampG** [okp4/portal-web#91]
The user should be able to come back to the portal's homepage thanks to the header. 
From now on, when we are on the Explorer, we can't reach it. 

![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/624a8970-c775-4a63-8998-6157af80ed0f)

**Comment by fredericvilcot** [comment]
@ErikssonJoakim 
Is it implemented on your side?

**Comment by ErikssonJoakim** [comment]
@fredericvilcot This has not been worked on yet.
